### ISSUE TITLE
Not really an issue sorry!

### ISSUE THREAD

**Issue by ghost** [Mark-B1/mark-b_police-tracker#1]
Don't know where else to ask but possibility on adding it so it can only be used in an emergency vehicle? and possible to have a range check? So that we have both a timer and a distance in which it will cut out. Sorry for asking here!

**Comment by Mark-B1** [comment]
> Don't know where else to ask but possibility on adding it so it can only be used in an emergency vehicle? and possible to have a range check? So that we have both a timer and a distance in which it will cut out. Sorry for asking here!

I will be pushing out an update for the tracker soonish as people over at the forums requested few things to be added. For your suggestion, I'll add a vehicle whitelist option based on the vehicle hash and a range limit as requested.
